"""initial schema

Revision ID: bc74ec0ff6c4
Revises: 
Create Date: 2026-03-18 13:59:08.791727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc74ec0ff6c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('required_approver', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('facilities',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('office_location', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('manager_email', sa.String(length=320), nullable=True),
    sa.Column('manager_name', sa.String(length=200), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('entra_id', sa.String(length=100), nullable=True),
    sa.Column('entra_groups', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_entra_id'), 'users', ['entra_id'], unique=True)
    op.create_table('departments',
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('budget_total', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entra_group_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entra_group_name', sa.String(length=200), nullable=False),
    sa.Column('app_role', sa.String(length=20), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entra_group_name')
    )
    op.create_table('facility_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'facility_id', name='uq_user_facility_perm')
    )
    op.create_table('transfer_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('source_facility_id', sa.UUID(), nullable=True),
    sa.Column('target_facility_id', sa.UUID(), nullable=True),
    sa.Column('transfer_mode', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_facility_id'], ['facilities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_facility_id'], ['facilities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_logs_entity_type'), 'transfer_logs', ['entity_type'], unique=False)
    op.create_table('budget_adjustments',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('PRODUCT_CHANGE', 'SUPPLIER_CHANGE', 'SCOPE_CHANGE', 'OPTIMIZATION', 'OTHER', name='adjustment_category', create_constraint=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_adjustments_department_id'), 'budget_adjustments', ['department_id'], unique=False)
    op.create_table('work_areas',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_items',
    sa.Column('work_area_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('expected_cash_out', sa.Date(), nullable=True),
    sa.Column('cost_basis', sa.String(length=50), nullable=True),
    sa.Column('cost_driver', sa.String(length=50), nullable=True),
    sa.Column('basis_description', sa.Text(), nullable=True),
    sa.Column('assumptions', sa.Text(), nullable=True),
    sa.Column('approval_status', sa.Enum('OPEN', 'SUBMITTED_FOR_APPROVAL', 'APPROVED', 'REJECTED', 'ON_HOLD', 'PENDING_SUPPLIER_NEGOTIATION', 'PENDING_TECHNICAL_CLARIFICATION', 'OBSOLETE', name='approval_status', create_constraint=True), server_default='OPEN', nullable=False),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('project_phase', sa.String(length=50), nullable=True),
    sa.Column('product', sa.String(length=50), nullable=True),
    sa.Column('zielanpassung', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('zielanpassung_reason', sa.Text(), nullable=True),
    sa.Column('requester', sa.String(length=200), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['work_area_id'], ['work_areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cost_items_approval_status', 'cost_items', ['approval_status'], unique=False)
    op.create_index('ix_cost_items_created_at', 'cost_items', ['created_at'], unique=False)
    op.create_index('ix_cost_items_current_amount', 'cost_items', ['current_amount'], unique=False)
    op.create_index('ix_cost_items_expected_cash_out', 'cost_items', ['expected_cash_out'], unique=False)
    op.create_index('ix_cost_items_product', 'cost_items', ['product'], unique=False)
    op.create_index('ix_cost_items_project_phase', 'cost_items', ['project_phase'], unique=False)
    op.create_index('ix_cost_items_work_area_id', 'cost_items', ['work_area_id'], unique=False)
    op.create_table('attachments',
    sa.Column('cost_item_id', sa.UUID(), nullable=True),
    sa.Column('work_area_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attachment_type', sa.Enum('OFFER', 'INVOICE', 'SPECIFICATION', 'PHOTO', 'OTHER', name='attachment_type', create_constraint=True), server_default='OTHER', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('((cost_item_id IS NOT NULL AND work_area_id IS NULL AND department_id IS NULL) OR (cost_item_id IS NULL AND work_area_id IS NOT NULL AND department_id IS NULL) OR (cost_item_id IS NULL AND work_area_id IS NULL AND department_id IS NOT NULL))', name='ck_attachment_exactly_one_parent'),
    sa.ForeignKeyConstraint(['cost_item_id'], ['cost_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_area_id'], ['work_areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.drop_index('ix_cost_items_work_area_id', table_name='cost_items')
    op.drop_index('ix_cost_items_project_phase', table_name='cost_items')
    op.drop_index('ix_cost_items_product', table_name='cost_items')
    op.drop_index('ix_cost_items_expected_cash_out', table_name='cost_items')
    op.drop_index('ix_cost_items_current_amount', table_name='cost_items')
    op.drop_index('ix_cost_items_created_at', table_name='cost_items')
    op.drop_index('ix_cost_items_approval_status', table_name='cost_items')
    op.drop_table('cost_items')
    op.drop_table('work_areas')
    op.drop_index(op.f('ix_budget_adjustments_department_id'), table_name='budget_adjustments')
    op.drop_table('budget_adjustments')
    op.drop_index(op.f('ix_transfer_logs_entity_type'), table_name='transfer_logs')
    op.drop_table('transfer_logs')
    op.drop_table('facility_permissions')
    op.drop_table('entra_group_mappings')
    op.drop_table('departments')
    op.drop_index(op.f('ix_users_entra_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
